import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/Navbar";
import SideNav from "@/components/SideNav";
import Head from "next/head";
import StoreProvider from "../StoreProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/AuthOptions";
import { redirect } from "next/navigation";
import ToastProvider from "@/providers/ToastProvider";
import { EdgeStoreProvider } from "@/lib/edgestore";
import Loading from "./loading";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  if(!session?.user?.email){
    redirect('/login');
  }
  return (
    <StoreProvider>
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Mukta:wght@200;300;400;500;600;700;800&display=swap"
        />
      </Head>
      <body className={`bg-[#F5F5F5] v_center flex-col`}>
      <ToastProvider />
        <div className="w-[1412px]">
          <Navbar />
          <div className="flex">
            <SideNav />
            <Suspense fallback={<Loading />}>
            <EdgeStoreProvider>
            {children}
            </EdgeStoreProvider>
            </Suspense>
          </div>
        </div>
      </body>
    </html>
    </StoreProvider>
  );
}
